# Generated by Django 5.1.5 on 2025-02-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateField(null=True),
        ),
    ]
